Issue 1779: Fix the java.lang.InstantiationException and java.lang.NoSuchMethodException reported in CronJobDuplicationCheckStrategiesRegistry with JDK11
* Fixed #1179 by re-working the `ThrowingFunction` and `CronJobDuplicationCheckStrategiesRegistry`, as there appear to be changes in the way that compiler handles generics for `Throwable` / `Exception` in JDK11.

Issue 1780: Fix the java.lang.NoClassDefFoundError: sun/reflect/Reflection in the strongbox-ldap-authentication-provider when building under JDK 11

* Fixed #1780 by dropping ApacheDS and replacing it with UnboundID. This is only used for testing purposes.

Issue 1111: Test our build with JDK 11 and fix any issues with it

* Introduced `LocalDateTimeInstance` and set the correct precision. This was breaking some tests. We should use `LocalDateTimeInstance.now()`, instead of just `LocalDateTime.now()`, as it's more precise.